#!/bin/bash
# Generated by OrchestKit Claude Plugin
# Created: 2026-03-06

# Silently checks if the RAG server is running. Warns if not.

STATUS=$(curl -s --max-time 2 http://localhost:8000/health 2>/dev/null)

if [ -z "$STATUS" ]; then
  echo "Academic Writer: Hybrid-Search-RAG server is not running. Start it with:"
  echo "  cd ~/dev/Hybrid-Search-RAG && uvicorn hybridrag.api.main:app --port 8000"
fi
