#!/bin/bash
# Generated by OrchestKit Claude Plugin
# Created: 2026-03-06

# Checks if researcher profile exists. If not, reminds them to run init.

PROFILE_PATH=".academic-writer/profile.json"

if [ ! -f "$PROFILE_PATH" ]; then
  echo "Academic Writer: No profile found. Run /academic-writer-init to get set up before writing your first article."
fi
